server:
  port: 8001
spring:
  application:
    name: normal
  datasource:
    druid:
      url: jdbc:mysql://47.107.225.141:3306/demo?useUnicode=true&characterEncoding=utf8
      username: root
      password: 6687686li


